In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing wine data into a pandas dataframe

In [2]:
winedf = pd.read_csv("winequality-red.csv", sep=';')

Make sure everything imported correctly

In [3]:
print(winedf.shape)
winedf.head()

(1599, 12)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

Check for any missing values

In [4]:
winedf.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

We're not sure that the data is completely clean yet. Let's try importing the data into numpy and see if there are any missing values:

In [5]:
wineData = winedf.to_numpy()
wineData

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

Checking for any NaN values in the matrix

In [6]:
np.isnan(wineData).astype(int).sum()

0

The data is clean.

Create a quality column with 1/0 labels for wines with a rating of 6 or higher

In [7]:
quality = (wineData[:,11]>=6).astype(int)

Append the column to the end of data array


In [8]:
wineData = np.c_[wineData, quality]
wineData

array([[ 7.4  ,  0.7  ,  0.   , ...,  9.4  ,  5.   ,  0.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  9.8  ,  5.   ,  0.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  9.8  ,  5.   ,  0.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ..., 11.   ,  6.   ,  1.   ],
       [ 5.9  ,  0.645,  0.12 , ..., 10.2  ,  5.   ,  0.   ],
       [ 6.   ,  0.31 ,  0.47 , ..., 11.   ,  6.   ,  1.   ]])

Import breast cancer data into a pandas dataframe

In [27]:
bcdf = pd.read_csv("breast-cancer-wisconsin.data", sep=',', header=None)

Add columns

In [28]:
bcdf.columns = ['Sample code', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses', 'Class']

Make sure everything imported correctly

In [29]:
print(bcdf.shape)
bcdf.head()

(699, 11)


Sample code  Clump Thickness  Uniformity of Cell Size  \
0      1000025                5                        1   
1      1002945                5                        4   
2      1015425                3                        1   
3      1016277                6                        8   
4      1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

Check for missing values

In [30]:
bcdf.isnull().sum()

Sample code                    0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

We're not sure that the data is completely clean yet. Let's try importing the data into numpy and see if there are any missing values:

In [31]:
bcData = np.genfromtxt("breast-cancer-wisconsin.data", delimiter=",")
bcData

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

Checking for any NaN values in the matrix

In [32]:
np.isnan(bcData).astype(int).sum()

16

No missing entries were found on the pandas dataframe but 16 were found using a numpy array. This probably means that the missing values are some non-numerical character. The text file accompanying the dataset shows this to be the '?' character. We need to replace this with a NaN character.

In [37]:
bcdf.replace('?', np.NaN, inplace=True)

16 missing entries: How many entries are missing per column?

In [38]:
bcdf.isna().sum()

Sample code                     0
Clump Thickness                 0
Uniformity of Cell Size         0
Uniformity of Cell Shape        0
Marginal Adhesion               0
Single Epithelial Cell Size     0
Bare Nuclei                    16
Bland Chromatin                 0
Normal Nucleoli                 0
Mitoses                         0
Class                           0
dtype: int64

We need to drop those rows with missing values.

Number of rows before drop:

In [40]:
bcdf.shape[0]

699

In [41]:
bcdf.dropna()

Sample code  Clump Thickness  Uniformity of Cell Size  \
0        1000025                5                        1   
1        1002945                5                        4   
2        1015425                3                        1   
3        1016277                6                        8   
4        1017023                4                        1   
5        1017122                8                       10   
6        1018099                1                        1   
7        1018561                2                        1   
8        1033078                2                        1   
9        1033078                4                        2   
10       1035283                1                        1   
11       1036172                2                        1   
12       1041801                5                        3   
13       1043999                1                        1   
14       1044572                8                        7   
15       1047630                7                        4   
16       1048672                4                        1   
17       1049815                4                        1   
18       1050670               10                        7   
19       1050718                6                        1   
20       1054590                7                        3   
21       1054593               10                        5   
22       1056784                3                        1   
24       1059552                1                        1   
25       1065726                5                        2   
26       1066373                3                        2   
27       1066979                5                        1   
28       1067444                2                        1   
29       1070935                1                        1   
30       1070935                3                        1   
..           ...              ...                      ...   
669      1350423                5                       10   
670      1352848                3                       10   
671      1353092                3                        2   
672      1354840                2                        1   
673      1354840                5                        3   
674      1355260                1                        1   
675      1365075                4                        1   
676      1365328                1                        1   
677      1368267                5                        1   
678      1368273                1                        1   
679      1368882                2                        1   
680      1369821               10                       10   
681      1371026                5                       10   
682      1371920                5                        1   
683       466906                1                        1   
684       466906                1                        1   
685       534555                1                        1   
686       536708                1                        1   
687       566346                3                        1   
688       603148                4                        1   
689       654546                1                        1   
690       654546                1                        1   
691       695091                5                       10   
692       714039                3                        1   
693       763235                3                        1   
694       776715                3                        1   
695       841769                2                        1   
696       888820                5                       10   
697       897471                4                        8   
698       897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2  

Number of rows before drop:

In [43]:
bcdf.shape[0]

699