In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing wine data into a pandas dataframe

In [90]:
winedf = pd.read_csv("winequality-red.csv", sep=';')

Make sure everything imported correctly

In [91]:
print(winedf.shape)
winedf.head()

(1599, 12)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

Check for any missing values

In [92]:
winedf.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

We're not sure that the data is completely clean yet. Let's try importing the data into numpy and see if there are any missing values:

In [132]:
wineData = winedf.to_numpy()
wineData

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

Checking for any NaN values in the matrix

In [133]:
np.isnan(wineData).astype(int).sum()

0

The data is clean.

Create a quality column with 1/0 labels for wines with a rating of 6 or higher

In [134]:
quality = (wineData[:,11]>=6).astype(int)

Append the column to the end of data array


In [136]:
wineData = np.c_[wineData, quality]
wineData

array([[7.4  , 0.7  , 0.   , ..., 5.   , 0.   , 0.   ],
       [7.8  , 0.88 , 0.   , ..., 5.   , 0.   , 0.   ],
       [7.8  , 0.76 , 0.04 , ..., 5.   , 0.   , 0.   ],
       ...,
       [6.3  , 0.51 , 0.13 , ..., 6.   , 1.   , 1.   ],
       [5.9  , 0.645, 0.12 , ..., 5.   , 0.   , 0.   ],
       [6.   , 0.31 , 0.47 , ..., 6.   , 1.   , 1.   ]])

Import breast cancer data into a pandas dataframe

In [96]:
bcdf = pd.read_csv("breast-cancer-wisconsin.data", sep=',', header=None)

Add columns

In [138]:
bcdf.columns = ['Sample code', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses', 'Class']

Make sure everything imported correctly

In [139]:
print(bcdf.shape)
bcdf.head()

(699, 11)


Sample code  Clump Thickness  Uniformity of Cell Size  \
0      1000025                5                        1   
1      1002945                5                        4   
2      1015425                3                        1   
3      1016277                6                        8   
4      1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

Check for missing values

In [140]:
bcdf.isnull().sum()

Sample code                    0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

We're not sure that the data is completely clean yet. Let's try importing the data into numpy and see if there are any missing values:

In [126]:
bcData = np.genfromtxt("breast-cancer-wisconsin.data", delimiter=",")
bcData

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

Checking for any NaN values in the matrix

In [125]:
np.isnan(bcData).astype(int).sum()

16