In [309]:
#Data cleaning and preprocessing
winedf = pd.read_csv("winequality-red.csv", sep=';')
wineData = winedf.to_numpy()
wineData[:,-1] = (wineData[:,-1]>=6).astype(int) #convert 6+ to 1 and <5 to 0
wineData = wineData/wineData.max(axis=0) #normalize data

bcdf = pd.read_csv("breast-cancer-wisconsin.data", sep=',', header=None)
bcdf.columns = ['Sample Code Number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses', 'Class']
bcdf.replace('?', np.NaN, inplace=True)
bcdf.dropna(inplace=True)
bcdf.drop(['Sample Code Number'], axis=1, inplace=True)
bcData = bcdf.to_numpy().astype(float)
bcData[:,-1] = (bcData[:,-1]>3).astype(int) #change 2/4 last column to 0/1 labels
bcData = bcData/bcData.max(axis=0) #normalize data

In [310]:
winedf

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [311]:
winedf.sample(frac=1)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
792             7.1             0.610         0.02            2.50      0.081   
1346            6.1             0.590         0.01            2.10      0.056   
1525            6.7             0.480         0.08            2.10      0.064   
602             7.7             0.835         0.00            2.60      0.081   
1024            7.7             0.580         0.01            1.80      0.088   
807             8.2             0.280         0.40            2.40      0.052   
628             8.7             0.540         0.26            2.50      0.097   
945            10.2             0.440         0.42            2.00      0.071   
1465            6.8             0.590         0.10            1.70      0.063   
1085            6.8             0.480         0.08            1.80      0.074   
159             6.8             0.600         0.18            1.90      0.079   
1071            7.5             0.770         0.20            8.10      0.098   
704             9.1             0.765         0.04            1.60      0.078   
1144            7.3             0.320         0.23            2.30      0.066   
762             8.8             0.700         0.00            1.70      0.069   
861             5.8             1.010         0.66            2.00      0.039   
331            10.2             0.360         0.64            2.90      0.122   
1585            7.2             0.390         0.44            2.60      0.066   
514            10.5             0.510         0.64            2.40      0.107   
1233           10.2             0.230         0.37            2.20      0.057   
101             7.8             0.500         0.30            1.90      0.075   
1455            6.5             0.900         0.00            1.60      0.052   
1229            7.6             0.430         0.29            2.10      0.075   
703             7.5             0.380         0.48            2.60      0.073   
1341            7.5             0.510         0.02            1.70      0.084   
948             8.9             0.120         0.45            1.80      0.075   
589            10.2             0.290         0.49            2.60      0.059   
1330            7.4             0.600         0.26            2.10      0.083   
1447            6.8             0.670         0.00            1.90      0.080   
1243            8.3             0.560         0.22            2.40      0.082   
...             ...               ...          ...             ...        ...   
71              7.7             0.670         0.23            2.10      0.088   
170             7.9             0.885         0.03            1.80      0.058   
1421            7.5             0.400         0.18            1.60      0.079   
1404            8.0             0.500         0.39            2.60      0.082   
201             8.8             0.370         0.48            2.10      0.097   
162             7.8             0.530         0.04            1.70      0.076   
941             9.9             0.270         0.49            5.00      0.082   
1165            8.5             0.440         0.50            1.90      0.369   
23              8.5             0.490         0.11            2.30      0.084   
1095            9.4             0.400         0.47            2.50      0.087   
981             9.5             0.860         0.26            1.90      0.079   
791             8.8             0.640         0.17            2.90      0.084   
1054            8.2             0.640         0.27            2.00      0.095   
1279            9.8             0.300         0.39            1.70      0.062   
1052            5.6             0.605         0.05            2.40      0.073   
734             7.7             0.560         0.20            2.00      0.075   
469             8.7             0.820         0.02            1.20      0.070   
40              7.3             0.450

In [312]:
winedf.apply(np.random.permutation)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0              11.6             0.320         0.10            2.20      0.063   
1               7.7             0.460         0.43            1.60      0.078   
2               7.3             0.740         0.50            2.90      0.081   
3               9.8             0.490         0.08            6.30      0.070   
4               7.1             0.460         0.49            2.10      0.067   
5               7.7             0.420         0.09            6.10      0.060   
6              10.3             0.520         0.44            2.10      0.076   
7               7.5             0.440         0.37            2.10      0.097   
8               7.1             0.630         0.49            2.30      0.122   
9               9.4             0.330         0.32            2.00      0.073   
10              8.0             0.710         0.40            3.10      0.084   
11             11.6             0.510         0.04            1.90      0.081   
12              9.5             0.400         0.64            2.00      0.103   
13              8.2             0.480         0.02            1.80      0.104   
14             10.1             0.625         0.23            1.90      0.165   
15             12.6             0.430         0.47            1.90      0.089   
16              6.8             0.480         0.24            1.20      0.087   
17              9.5             0.740         0.42            1.80      0.091   
18              9.9             0.430         0.28            3.45      0.084   
19              7.2             1.130         0.48            2.40      0.097   
20              6.8             0.400         0.42            2.00      0.072   
21              7.9             0.560         0.12            3.70      0.077   
22              6.5             0.615         0.10            2.00      0.070   
23              8.9             0.730         0.10            1.70      0.091   
24              8.8             0.410         0.47            1.80      0.077   
25             11.5             0.745         0.52            2.40      0.055   
26              9.9             0.705         0.49            2.50      0.076   
27              6.9             0.440         0.13            5.80      0.047   
28              7.6             0.410         0.42            2.30      0.078   
29              7.0             0.400         0.31            5.20      0.106   
...             ...               ...          ...             ...        ...   
1569            8.0             0.550         0.39            1.50      0.049   
1570            7.1             0.540         0.39            5.90      0.111   
1571            9.4             0.400         0.02            1.90      0.065   
1572            7.3             0.370         0.24            2.90      0.168   
1573            8.9             0.490         0.26            2.10      0.080   
1574           10.9             0.320         0.49            3.80      0.054   
1575            5.6             0.630         0.00            1.80      0.096   
1576            7.6             0.590         0.52            2.20      0.098   
1577            8.5             0.980         0.57            1.80      0.078   
1578           10.0             0.320         0.11            2.10      0.082   
1579            7.8             0.570         0.04            1.90      0.083   
1580            6.7             0.685         0.00            1.60      0.074   
1581            8.8             0.590         0.36            1.80      0.061   
1582            7.8             0.370         0.26            1.80      0.048   
1583            7.7             0.620         0.49            2.50      0.101   
1584            5.4             0.660         0.28            1.40      0.066   
1585            8.2             0.500         0.34            1.70      0.095   
1586           11.6             0.420

In [313]:
wineData

array([[0.46540881, 0.44303797, 0.        , ..., 0.28      , 0.63087248,
        0.        ],
       [0.49056604, 0.55696203, 0.        , ..., 0.34      , 0.65771812,
        0.        ],
       [0.49056604, 0.48101266, 0.04      , ..., 0.325     , 0.65771812,
        0.        ],
       ...,
       [0.39622642, 0.32278481, 0.13      , ..., 0.375     , 0.73825503,
        1.        ],
       [0.37106918, 0.40822785, 0.12      , ..., 0.355     , 0.68456376,
        0.        ],
       [0.37735849, 0.19620253, 0.47      , ..., 0.33      , 0.73825503,
        1.        ]])

In [315]:
np.random.shuffle(wineData)

In [318]:
wineData

array([[0.48427673, 0.14556962, 0.37      , ..., 0.355     , 0.81208054,
        1.        ],
       [0.44654088, 0.41772152, 0.        , ..., 0.27      , 0.63758389,
        0.        ],
       [0.52201258, 0.31012658, 0.36      , ..., 0.3       , 0.63758389,
        1.        ],
       ...,
       [0.4591195 , 0.21518987, 0.33      , ..., 0.385     , 0.81208054,
        1.        ],
       [0.40251572, 0.36075949, 0.02      , ..., 0.34      , 0.63758389,
        0.        ],
       [0.63522013, 0.59177215, 0.22      , ..., 0.32      , 0.75838926,
        0.        ]])

In [354]:
a = np.random.random((16,2))
a

array([[0.13197048, 0.68582093],
       [0.63276899, 0.78579744],
       [0.4141059 , 0.22643447],
       [0.72479661, 0.95539378],
       [0.06406458, 0.52054522],
       [0.05448336, 0.37520599],
       [0.34230404, 0.35761793],
       [0.33852436, 0.64159963],
       [0.02506208, 0.00859959],
       [0.15411788, 0.68878295],
       [0.02885691, 0.63069336],
       [0.17730013, 0.32705496],
       [0.38952074, 0.88524601],
       [0.04167986, 0.08812843],
       [0.92373875, 0.52946077],
       [0.99724383, 0.12632496]])

In [391]:
foldsList = np.array_split(a, 4)

In [392]:
for foldIndex, currentFold in enumerate(foldsList):
    print(foldIndex)

0
1
2
3


In [393]:
len(b)

4

In [394]:
a = [1, 2, 4]
b = a[:]
b.insert(2, 3)

In [395]:
a

[1, 2, 4]

In [396]:
b

[1, 2, 3, 4]

In [397]:
a = ['a', 'b']

In [398]:
a

['a', 'b']

In [399]:
a.insert(9, 'c')

In [400]:
a

['a', 'b', 'c']

In [402]:
for foldIndex, currentFold in enumerate(foldsList):
    validationData = currentFold #assign current fold value to validationData
    foldsList.remove(currentFold) #remove the current fold from the list
    trainingData = np.vstack(foldsList)
    # vertically stack the remaining elements in the list creating a matrix of
    # the dataset with validation data removed --> creating the training set
    foldsList.insert(foldIndex, currentFold)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [387]:
validationData

array([[0.06406458, 0.52054522],
       [0.05448336, 0.37520599],
       [0.34230404, 0.35761793],
       [0.33852436, 0.64159963]])

In [390]:
len(foldsList)

4

In [403]:
foldsList = np.array_split(a, 4)

In [404]:
foldsList

[array(['a'], dtype='<U1'),
 array(['b'], dtype='<U1'),
 array(['c'], dtype='<U1'),
 array([], dtype='<U1')]

In [413]:
a = np.random.random((16,2))

In [414]:
a

array([[0.16957144, 0.74934758],
       [0.5807946 , 0.2636175 ],
       [0.65394189, 0.76193237],
       [0.69894282, 0.72840904],
       [0.1120781 , 0.10677641],
       [0.03919939, 0.83714064],
       [0.66882443, 0.94166158],
       [0.13469757, 0.40422441],
       [0.37952948, 0.24804356],
       [0.83577322, 0.22739505],
       [0.29891381, 0.96941245],
       [0.97218107, 0.97850869],
       [0.10194472, 0.24220638],
       [0.65841721, 0.08252444],
       [0.98004541, 0.72116683],
       [0.23907695, 0.10749088]])

In [415]:
foldsList = np.array_split(a, 4)

In [416]:
foldsList

[array([[0.16957144, 0.74934758],
        [0.5807946 , 0.2636175 ],
        [0.65394189, 0.76193237],
        [0.69894282, 0.72840904]]), array([[0.1120781 , 0.10677641],
        [0.03919939, 0.83714064],
        [0.66882443, 0.94166158],
        [0.13469757, 0.40422441]]), array([[0.37952948, 0.24804356],
        [0.83577322, 0.22739505],
        [0.29891381, 0.96941245],
        [0.97218107, 0.97850869]]), array([[0.10194472, 0.24220638],
        [0.65841721, 0.08252444],
        [0.98004541, 0.72116683],
        [0.23907695, 0.10749088]])]

In [417]:
for i in range(4):
    valData = foldsList[i]
    del foldsList[i]
    trData = np.vstack(foldsList)
    foldsList.insert(i, valData)

In [418]:
valData

array([[0.10194472, 0.24220638],
       [0.65841721, 0.08252444],
       [0.98004541, 0.72116683],
       [0.23907695, 0.10749088]])

In [420]:
len(foldsList)

4